[package]
name = "MiaOS"
version = "0.1.0"
edition = "2018"

# cargo build 时禁用栈展开
[profile.dev] 
panic="abort"
# cargo build --release 时禁用栈展开
[profile.release]
panic="abort"
debug = true

[dependencies]
sbi-rt = { version = "0.0.2", features = ["legacy"] }
